#!/bin/sh
# Compiles camera_background.mat and embeds the result as a Kotlin constant.
# Usage: koord/materials/embed.sh /path/to/matc
set -eu
matc=${1:?usage: embed.sh /path/to/matc}
dir=$(cd "$(dirname "$0")" && pwd)
out="$dir/../src/androidMain/kotlin/io/github/erkko68/koord/camera/CameraBackgroundMaterial.kt"
tmp=$(mktemp)
"$matc" -p mobile -a opengl -o "$tmp" "$dir/camera_background.mat"
{
    echo "package io.github.erkko68.koord.camera"
    echo
    echo "// Generated by koord/materials/embed.sh from camera_background.mat; do not edit."
    echo "internal const val CAMERA_BACKGROUND_FILAMAT_BASE64 ="
    base64 < "$tmp" | tr -d '\n' | fold -w 100 | sed 's/.*/    "&" +/'
    echo '    ""'
} > "$out"
rm "$tmp"
